const roles=["Front-End Developer","UI/UX Enthusiast","Creative Coder","Javascript Specialist"];let roleIndex=0;let charIndex=0;let isDeleting=!1;const roleTextElement=document.getElementById('roleText');function typeRole(){if(!roleTextElement)return;const currentRole=roles[roleIndex];if(isDeleting){charIndex--;roleTextElement.textContent=currentRole.substring(0,charIndex);if(charIndex===0){isDeleting=!1;roleIndex=(roleIndex+1)%roles.length;setTimeout(typeRole,500)}else{setTimeout(typeRole,50)}}else{charIndex++;roleTextElement.textContent=currentRole.substring(0,charIndex);if(charIndex===currentRole.length){isDeleting=!0;setTimeout(typeRole,2000)}else{setTimeout(typeRole,100)}}}
function setupButtonHandlers(){const viewWorkBtn=document.getElementById('viewWorkBtn');const contactBtn=document.getElementById('contactBtn');const scrollIndicator=document.querySelector('.scroll-indicator');if(viewWorkBtn){viewWorkBtn.addEventListener('click',()=>{const projectsSection=document.getElementById('projects');if(projectsSection){const offsetTop=projectsSection.offsetTop-70;window.scrollTo({top:offsetTop,behavior:'smooth'})}})}
if(contactBtn){contactBtn.addEventListener('click',()=>{const contactSection=document.getElementById('contact');if(contactSection){const offsetTop=contactSection.offsetTop-70;window.scrollTo({top:offsetTop,behavior:'smooth'})}})}
if(scrollIndicator){scrollIndicator.addEventListener('click',()=>{const aboutSection=document.getElementById('about');if(aboutSection){const offsetTop=aboutSection.offsetTop-70;window.scrollTo({top:offsetTop,behavior:'smooth'})}})}}
let statsAnimated=!1;function animateStats(){if(statsAnimated)return;const aboutSection=document.getElementById('about');if(!aboutSection)return;const sectionPosition=aboutSection.getBoundingClientRect().top;const screenPosition=window.innerHeight/1.3;if(sectionPosition<screenPosition){statsAnimated=!0;const counters=[{element:document.getElementById('yearsExp'),target:1,suffix:'+'},{element:document.getElementById('projectsDone'),target:5,suffix:'+'},{element:document.getElementById('happyClients'),target:10,suffix:'+'}];counters.forEach(counter=>{if(!counter.element)return;let current=0;const increment=Math.ceil(counter.target/50);const updateCounter=()=>{if(current<counter.target){current+=increment;if(current>counter.target)current=counter.target;counter.element.textContent=current+(counter.suffix||'');setTimeout(updateCounter,30)}};updateCounter()})}}
let skillsAnimated=!1;function animateSkillBars(){if(skillsAnimated)return;const skillsSection=document.getElementById('skills');if(!skillsSection)return;const sectionPosition=skillsSection.getBoundingClientRect().top;const screenPosition=window.innerHeight/1.2;if(sectionPosition<screenPosition){skillsAnimated=!0;const skillBars=document.querySelectorAll('.skill-progress');skillBars.forEach(bar=>{const width=bar.getAttribute('data-width');if(width){setTimeout(()=>{bar.style.width=width+'%'},200)}})}}
function revealOnScroll(){const revealElements=document.querySelectorAll('.scroll-reveal');revealElements.forEach(element=>{const elementPosition=element.getBoundingClientRect().top;const screenPosition=window.innerHeight-100;if(elementPosition<screenPosition){element.classList.add('revealed')}})}
function setupProjectFilters(){const filterButtons=document.querySelectorAll('.filter-btn');const projectCards=document.querySelectorAll('.project-card');filterButtons.forEach(button=>{button.addEventListener('click',()=>{filterButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');const filterValue=button.getAttribute('data-filter');projectCards.forEach(card=>{if(filterValue==='all'||card.getAttribute('data-category')===filterValue){card.classList.remove('hide');card.style.opacity='0';card.style.transform='translateY(20px)';setTimeout(()=>{card.style.opacity='1';card.style.transform='translateY(0)'},50)}else{card.classList.add('hide')}})})})}
function revealProjects(){const projectCards=document.querySelectorAll('.project-card');projectCards.forEach(card=>{const cardPosition=card.getBoundingClientRect().top;const screenPosition=window.innerHeight-100;if(cardPosition<screenPosition){card.classList.add('revealed')}})}
function heroParallax(){const heroContent=document.querySelector('.hero-content');if(!heroContent)return;window.addEventListener('scroll',()=>{const scrollPosition=window.scrollY;if(scrollPosition>0){heroContent.style.opacity=1-scrollPosition/500;heroContent.style.transform=`translateY(${scrollPosition * 0.3}px)`}else{heroContent.style.opacity=1;heroContent.style.transform='translateY(0)'}})}
document.addEventListener('DOMContentLoaded',()=>{const navLinksContainer=document.getElementById('navLinks');if(window.innerWidth>768){setTimeout(()=>{navLinksContainer.classList.add('animate')},300)}
const hamburger=document.getElementById('hamburger');const navLinks=document.getElementById('navLinks');const navItems=document.querySelectorAll('.nav-link');hamburger.addEventListener('click',()=>{hamburger.classList.toggle('active');navLinks.classList.toggle('active');document.body.style.overflow=navLinks.classList.contains('active')?'hidden':''});navItems.forEach(link=>{link.addEventListener('click',()=>{hamburger.classList.remove('active');navLinks.classList.remove('active');document.body.style.overflow=''})});window.addEventListener('resize',()=>{if(window.innerWidth>768){hamburger.classList.remove('active');navLinks.classList.remove('active');document.body.style.overflow=''}});const sections=document.querySelectorAll('section');const navLinksArr=document.querySelectorAll('.nav-link');function updateActiveSection(){let current='';const scrollPosition=window.scrollY+150;sections.forEach(section=>{const sectionTop=section.offsetTop;const sectionHeight=section.clientHeight;if(scrollPosition>=sectionTop&&scrollPosition<sectionTop+sectionHeight){current=section.getAttribute('id')}});navLinksArr.forEach(link=>{link.classList.remove('active');const href=link.getAttribute('href').substring(1);if(href===current)link.classList.add('active');})}
updateActiveSection();window.addEventListener('scroll',updateActiveSection);navLinksArr.forEach(link=>{link.addEventListener('click',(e)=>{e.preventDefault();const targetId=link.getAttribute('href').substring(1);const targetSection=document.getElementById(targetId);if(targetSection){const offsetTop=targetSection.offsetTop-70;window.scrollTo({top:offsetTop,behavior:'smooth'})}})});const navbar=document.getElementById('navbar');window.addEventListener('scroll',()=>{if(window.scrollY>50){navbar.style.background='rgba(10, 10, 15, 0.9)';navbar.style.backdropFilter='blur(16px)'}else{navbar.style.background='rgba(10, 10, 15, 0.7)';navbar.style.backdropFilter='blur(12px)'}});setupButtonHandlers();setupProjectFilters();heroParallax();setTimeout(()=>{if(roleTextElement)typeRole();},500);setTimeout(()=>{animateStats();animateSkillBars();revealOnScroll();revealProjects()},300);window.addEventListener('scroll',()=>{animateStats();animateSkillBars();revealOnScroll();revealProjects()});function createParticles(){const experienceSection=document.getElementById('experience');if(!experienceSection)return;const oldContainer=experienceSection.querySelector('.particle-container');if(oldContainer)oldContainer.remove();const particleContainer=document.createElement('div');particleContainer.classList.add('particle-container');experienceSection.style.position='relative';experienceSection.appendChild(particleContainer);const numberOfParticles=60;for(let i=0;i<numberOfParticles;i++){const particle=document.createElement('div');particle.classList.add('particle');if(Math.random()>0.7){particle.classList.add('large')}
const startX=Math.random()*100;const startY=Math.random()*100;particle.style.left=startX+'%';particle.style.top=startY+'%';const tx=(Math.random()-0.5)*200;const ty=(Math.random()-0.5)*150;particle.style.setProperty('--tx',tx+'px');particle.style.setProperty('--ty',ty+'px');const duration=6+Math.random()*6;particle.style.animationDuration=duration+'s';particle.style.animationDelay=Math.random()*10+'s';particleContainer.appendChild(particle)}}
let resizeTimeout;window.addEventListener('resize',()=>{clearTimeout(resizeTimeout);resizeTimeout=setTimeout(()=>{createParticles()},200)});setTimeout(()=>{createParticles()},500);function copyEmail(){const emailElement=document.getElementById('contactEmail');if(!emailElement)return;const email=emailElement.textContent;navigator.clipboard.writeText(email).then(()=>{showToast('Email copied to clipboard!','success')}).catch(()=>{showToast('Failed to copy email','error')})}
function showToast(message,type='success'){const existingToast=document.querySelector('.toast-notification');if(existingToast)existingToast.remove();const toast=document.createElement('div');toast.className='toast-notification';toast.innerHTML=`
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M20 6L9 17L4 12" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span>${message}</span>
    `;document.body.appendChild(toast);setTimeout(()=>{if(toast.parentNode)toast.remove();},3000)}});function setupContactForm(){emailjs.init("HH4bsKfTVlgc1prkI");const form=document.getElementById('contactForm');const formMessage=document.getElementById('formMessage');if(!form)return;form.addEventListener('submit',async(e)=>{e.preventDefault();const name=document.getElementById('name').value;const email=document.getElementById('email').value;const message=document.getElementById('message').value;if(!name||!email||!message){showFormMessage('Please fill in all fields','error');return}
if(!email.includes('@')||!email.includes('.')){showFormMessage('Please enter a valid email address','error');return}
const submitBtn=form.querySelector('.submit-btn');const originalText=submitBtn.innerHTML;submitBtn.innerHTML='Sending...';submitBtn.disabled=!0;try{await emailjs.send('service_xmhjvix','template_197z2qd',{from_name:name,from_email:email,message:message});showFormMessage('Message sent successfully! I\'ll get back to you soon.','success');form.reset()}catch(error){console.error('EmailJS error:',error);showFormMessage('Failed to send message. Please try again.','error')}finally{submitBtn.innerHTML=originalText;submitBtn.disabled=!1}})}
function showFormMessage(msg,type){const formMessage=document.getElementById('formMessage');if(formMessage){formMessage.textContent=msg;formMessage.className=`form-message ${type}`;setTimeout(()=>{formMessage.textContent='';formMessage.className='form-message'},5000)}}
function copyEmail(){const emailElement=document.getElementById('contactEmail');if(!emailElement)return;const email=emailElement.textContent;navigator.clipboard.writeText(email).then(()=>{showToast('Email copied to clipboard!','success')}).catch(()=>{showToast('Failed to copy email','error')})}
function showToast(message,type='success'){const existingToast=document.querySelector('.toast-notification');if(existingToast)existingToast.remove();const toast=document.createElement('div');toast.className='toast-notification';toast.innerHTML=`
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M20 6L9 17L4 12" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span>${message}</span>
    `;document.body.appendChild(toast);setTimeout(()=>{if(toast.parentNode)toast.remove();},3000)}
document.addEventListener('DOMContentLoaded',()=>{setupContactForm();const copyBtn=document.getElementById('copyEmailBtn');if(copyBtn){copyBtn.addEventListener('click',copyEmail)}});let allTestimonials=[];let currentPage=1;const itemsPerPage=3;let isLoading=!1;let loadTimeout=null;let adminMode=!1;function generateId(){return Date.now()+Math.random()}
function initTestimonialsData(){const stored=localStorage.getItem('testimonials');if(stored){allTestimonials=JSON.parse(stored)}else{allTestimonials=[{id:generateId(),name:"Sarah Johnson",job:"CEO, TechFlow",rating:5,comment:"Absolutely outstanding work! TiMi transformed our web presence completely."},{id:generateId(),name:"Michael Chen",job:"Product Manager",rating:5,comment:"A true professional. Delivered ahead of schedule and exceeded expectations."},{id:generateId(),name:"Jessica Williams",job:"Marketing Director",rating:4,comment:"Great attention to detail. Our website traffic increased significantly after the redesign."},{id:generateId(),name:"David Rodriguez",job:"Startup Founder",rating:5,comment:"TiMi brought our vision to life with modern design and flawless execution."},{id:generateId(),name:"Emily Davis",job:"UX Designer",rating:4,comment:"Collaborating with TiMi is a joy. He implements designs perfectly."},{id:generateId(),name:"James Wilson",job:"CTO, WebDev Studio",rating:5,comment:"Exceptional developer with superb problem-solving skills."},{id:generateId(),name:"Linda Martinez",job:"E-commerce Owner",rating:4,comment:"My online store looks amazing and runs smoothly. Thanks TiMi!"},{id:generateId(),name:"Robert Brown",job:"Project Lead",rating:5,comment:"Reliable, skilled, and always willing to go the extra mile."}];saveTestimonials()}}
function saveTestimonials(){localStorage.setItem('testimonials',JSON.stringify(allTestimonials))}
function getFilteredTestimonials(){return allTestimonials.filter(t=>t.rating>=4).sort((a,b)=>b.id-a.id)}
function getTotalPages(){const filtered=getFilteredTestimonials();return Math.ceil(filtered.length/itemsPerPage)}
function getCurrentPageItems(){const filtered=getFilteredTestimonials();const start=(currentPage-1)*itemsPerPage;const end=start+itemsPerPage;return filtered.slice(start,end)}
function renderTestimonialsList(){const items=getCurrentPageItems();const container=document.getElementById('testimonialsList');container.innerHTML='';items.forEach(t=>{const stars='★'.repeat(t.rating)+'☆'.repeat(5-t.rating);const card=document.createElement('div');card.className='testimonial-card';card.innerHTML=`
            <div class="testimonial-header">
                <div class="testimonial-author">
                    <h4>${escapeHtml(t.name)}</h4>
                    <p>${escapeHtml(t.job)}</p>
                </div>
                <div class="testimonial-rating">${stars}</div>
                ${adminMode ? `<button class="delete-icon" data-id="${t.id}">🗑️</button>` : ''}
            </div>
            <div class="testimonial-comment">“${escapeHtml(t.comment)}”</div>
        `;container.appendChild(card)});if(adminMode){document.querySelectorAll('.delete-icon').forEach(btn=>{btn.addEventListener('click',(e)=>{const id=parseFloat(btn.getAttribute('data-id'));deleteTestimonial(id)})})}
const totalPages=getTotalPages();const loadMoreContainer=document.getElementById('loadMoreContainer');const loadMoreBtn=document.getElementById('loadMoreBtn');if(totalPages<=1){loadMoreContainer.style.display='none';return}
loadMoreContainer.style.display='block';if(currentPage<totalPages){loadMoreBtn.textContent=`Load More (${currentPage + 1}/${totalPages})`;loadMoreBtn.onclick=()=>{if(isLoading)return;loadMore()}}else if(currentPage===totalPages){loadMoreBtn.textContent='Back to Start';loadMoreBtn.onclick=()=>{if(isLoading)return;currentPage=1;renderTestimonialsList()}}}
function deleteTestimonial(id){const index=allTestimonials.findIndex(t=>t.id===id);if(index!==-1){allTestimonials.splice(index,1);saveTestimonials();updateRatingSummary();const filtered=getFilteredTestimonials();const totalPages=Math.ceil(filtered.length/itemsPerPage);if(currentPage>totalPages&&totalPages>0){currentPage=totalPages}else if(filtered.length===0){currentPage=1}
renderTestimonialsList()}}
function loadMore(){if(isLoading)return;const totalPages=getTotalPages();if(currentPage>=totalPages)return;isLoading=!0;const loadMoreBtn=document.getElementById('loadMoreBtn');loadMoreBtn.disabled=!0;let dotCount=0;const loadingText=()=>{const dots='.'.repeat(dotCount%4);loadMoreBtn.textContent=`Loading${dots}`;dotCount++;if(dotCount<=20){loadTimeout=setTimeout(loadingText,300)}else{finishLoading()}};loadingText();function finishLoading(){if(loadTimeout)clearTimeout(loadTimeout);currentPage++;renderTestimonialsList();isLoading=!1;loadMoreBtn.disabled=!1}}
function updateRatingSummary(){const total=allTestimonials.length;if(total===0){document.getElementById('avgScore').innerText='0.0';document.getElementById('avgStars').innerHTML='☆☆☆☆☆';document.getElementById('totalRatings').innerText='(0 ratings)';for(let i=1;i<=5;i++){document.getElementById(`bar${i}`).style.width='0%';document.getElementById(`percent${i}`).innerText='0%'}
return}
let sum=0;const counts={1:0,2:0,3:0,4:0,5:0};allTestimonials.forEach(t=>{sum+=t.rating;counts[t.rating]++});const avg=sum/total;document.getElementById('avgScore').innerText=avg.toFixed(1);const fullStars=Math.floor(avg);const half=avg%1>=0.5;let starsHtml='';for(let i=1;i<=5;i++){if(i<=fullStars)starsHtml+='★';else if(i===fullStars+1&&half)starsHtml+='½';else starsHtml+='☆'}
document.getElementById('avgStars').innerHTML=starsHtml;document.getElementById('totalRatings').innerText=`(${total} ratings)`;for(let i=1;i<=5;i++){const percent=(counts[i]/total)*100;document.getElementById(`bar${i}`).style.width=percent+'%';document.getElementById(`percent${i}`).innerText=Math.round(percent)+'%'}}
function addTestimonial(name,job,rating,comment){const newTestimonial={id:generateId(),name:name.trim(),job:job.trim(),rating:parseInt(rating),comment:comment.trim()};allTestimonials.push(newTestimonial);saveTestimonials();updateRatingSummary();currentPage=1;renderTestimonialsList()}
function escapeHtml(str){if(!str)return'';return str.replace(/[&<>]/g,function(m){if(m==='&')return'&amp;';if(m==='<')return'&lt;';if(m==='>')return'&gt;';return m})}
function setupModal(){const modal=document.getElementById('testimonialModal');const openBtn=document.getElementById('openModalBtn');const closeSpan=document.querySelector('.close-modal');const form=document.getElementById('testimonialForm');const starSpans=document.querySelectorAll('.stars-input span');const ratingInput=document.getElementById('testimonialRating');openBtn.onclick=()=>modal.style.display='flex';closeSpan.onclick=()=>modal.style.display='none';window.onclick=(e)=>{if(e.target===modal)modal.style.display='none'};starSpans.forEach(span=>{span.addEventListener('click',()=>{const val=parseInt(span.getAttribute('data-value'));ratingInput.value=val;starSpans.forEach(s=>{if(parseInt(s.getAttribute('data-value'))<=val){s.classList.add('active')}else{s.classList.remove('active')}})})});starSpans.forEach(s=>{if(parseInt(s.getAttribute('data-value'))<=5)s.classList.add('active');});form.onsubmit=(e)=>{e.preventDefault();const name=document.getElementById('testimonialName').value;const job=document.getElementById('testimonialJob').value;const rating=ratingInput.value;const comment=document.getElementById('testimonialComment').value;if(!name||!job||!comment){alert('Please fill all fields');return}
addTestimonial(name,job,rating,comment);modal.style.display='none';form.reset();ratingInput.value=5;starSpans.forEach(s=>{if(parseInt(s.getAttribute('data-value'))<=5)s.classList.add('active');else s.classList.remove('active')})}}
function setupAdminMode(){const adminBtn=document.getElementById('adminModeBtn');adminBtn.addEventListener('click',()=>{if(!adminMode){const pwd=prompt('Enter password to enable Admin Mode');if(pwd==='Timzzylemmy1.'){adminMode=!0;adminBtn.textContent='🔓 Admin Mode (ON)';adminBtn.style.background='rgba(99,102,241,0.2)';renderTestimonialsList()}else{alert('Wrong password')}}else{adminMode=!1;adminBtn.textContent='🔒 Admin Mode';adminBtn.style.background='';renderTestimonialsList()}})}
function initTestimonials(){initTestimonialsData();updateRatingSummary();currentPage=1;renderTestimonialsList();setupModal();setupAdminMode()}
document.addEventListener('DOMContentLoaded',initTestimonials);function initFooter(){const yearSpan=document.getElementById('currentYear');if(yearSpan){yearSpan.textContent=new Date().getFullYear()}
const backToTopBtn=document.getElementById('backToTopBtn');if(backToTopBtn){window.addEventListener('scroll',()=>{if(window.scrollY>300){backToTopBtn.classList.add('visible')}else{backToTopBtn.classList.remove('visible')}});backToTopBtn.addEventListener('click',()=>{window.scrollTo({top:0,behavior:'smooth'})})}}
document.addEventListener('DOMContentLoaded',()=>{initFooter()});function initContactPopup(){const popupBtn=document.getElementById('contactPopupBtn');const modal=document.getElementById('contactModal');const closeBtn=document.getElementById('closeModalBtn');if(!popupBtn||!modal)return;popupBtn.addEventListener('click',(e)=>{e.preventDefault();modal.classList.add('active');document.body.style.overflow='hidden'});function closeModal(){modal.classList.remove('active');document.body.style.overflow=''}
if(closeBtn){closeBtn.addEventListener('click',closeModal)}
modal.addEventListener('click',(e)=>{if(e.target===modal){closeModal()}});document.addEventListener('keydown',(e)=>{if(e.key==='Escape'&&modal.classList.contains('active')){closeModal()}})}
document.addEventListener('contextmenu',(e)=>{e.preventDefault();return!1});document.addEventListener('DOMContentLoaded',()=>{initContactPopup()})